// Launchpad ABIs, from EkuboProtocol/evm-contracts at
// 40e5bb11f7d4a8b40bb40232027fa7888052eacb (PR #380):
//   SCHEDULED_LAUNCH_ABI         src/extensions/ScheduledLaunch.sol
//   LOCKED_LAUNCH_LIQUIDITY_ABI  src/LockedLaunchLiquidity.sol
//   LAUNCH_ROUTER_ABI            src/LaunchRouter.sol
// Regenerate with `forge inspect <path>:<Contract> abi --json` at that commit.

export const SCHEDULED_LAUNCH_ABI = [
  {
    type: "constructor",
    inputs: [
      { name: "core", type: "address", internalType: "contract ICore" },
      { name: "twamm", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "LIQUIDITY",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract LockedLaunchLiquidity",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "TWAMM",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "advance",
    inputs: [
      {
        name: "key",
        type: "tuple",
        internalType: "struct PoolKey",
        components: [
          { name: "token0", type: "address", internalType: "address" },
          { name: "token1", type: "address", internalType: "address" },
          { name: "config", type: "bytes32", internalType: "PoolConfig" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "afterCollectFees",
    inputs: [
      { name: "", type: "bytes32", internalType: "Locker" },
      {
        name: "",
        type: "tuple",
        internalType: "struct PoolKey",
        components: [
          { name: "token0", type: "address", internalType: "address" },
          { name: "token1", type: "address", internalType: "address" },
          { name: "config", type: "bytes32", internalType: "PoolConfig" },
        ],
      },
      { name: "", type: "bytes32", internalType: "PositionId" },
      { name: "", type: "uint128", internalType: "uint128" },
      { name: "", type: "uint128", internalType: "uint128" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "afterInitializePool",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      {
        name: "",
        type: "tuple",
        internalType: "struct PoolKey",
        components: [
          { name: "token0", type: "address", internalType: "address" },
          { name: "token1", type: "address", internalType: "address" },
          { name: "config", type: "bytes32", internalType: "PoolConfig" },
        ],
      },
      { name: "", type: "int32", internalType: "int32" },
      { name: "", type: "uint96", internalType: "SqrtRatio" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "afterSwap",
    inputs: [
      { name: "", type: "bytes32", internalType: "Locker" },
      {
        name: "",
        type: "tuple",
        internalType: "struct PoolKey",
        components: [
          { name: "token0", type: "address", internalType: "address" },
          { name: "token1", type: "address", internalType: "address" },
          { name: "config", type: "bytes32", internalType: "PoolConfig" },
        ],
      },
      { name: "", type: "bytes32", internalType: "SwapParameters" },
      { name: "", type: "bytes32", internalType: "PoolBalanceUpdate" },
      { name: "", type: "bytes32", internalType: "PoolState" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "afterUpdatePosition",
    inputs: [
      { name: "", type: "bytes32", internalType: "Locker" },
      {
        name: "",
        type: "tuple",
        internalType: "struct PoolKey",
        components: [
          { name: "token0", type: "address", internalType: "address" },
          { name: "token1", type: "address", internalType: "address" },
          { name: "config", type: "bytes32", internalType: "PoolConfig" },
        ],
      },
      { name: "", type: "bytes32", internalType: "PositionId" },
      { name: "", type: "int128", internalType: "int128" },
      { name: "", type: "bytes32", internalType: "PoolBalanceUpdate" },
      { name: "", type: "bytes32", internalType: "PoolState" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "beforeCollectFees",
    inputs: [
      { name: "", type: "bytes32", internalType: "Locker" },
      {
        name: "",
        type: "tuple",
        internalType: "struct PoolKey",
        components: [
          { name: "token0", type: "address", internalType: "address" },
          { name: "token1", type: "address", internalType: "address" },
          { name: "config", type: "bytes32", internalType: "PoolConfig" },
        ],
      },
      { name: "", type: "bytes32", internalType: "PositionId" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "beforeInitializePool",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      {
        name: "",
        type: "tuple",
        internalType: "struct PoolKey",
        components: [
          { name: "token0", type: "address", internalType: "address" },
          { name: "token1", type: "address", internalType: "address" },
          { name: "config", type: "bytes32", internalType: "PoolConfig" },
        ],
      },
      { name: "", type: "int32", internalType: "int32" },
    ],
    outputs: [],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "beforeSwap",
    inputs: [
      { name: "", type: "bytes32", internalType: "Locker" },
      {
        name: "",
        type: "tuple",
        internalType: "struct PoolKey",
        components: [
          { name: "token0", type: "address", internalType: "address" },
          { name: "token1", type: "address", internalType: "address" },
          { name: "config", type: "bytes32", internalType: "PoolConfig" },
        ],
      },
      { name: "", type: "bytes32", internalType: "SwapParameters" },
    ],
    outputs: [],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "beforeUpdatePosition",
    inputs: [
      { name: "", type: "bytes32", internalType: "Locker" },
      {
        name: "",
        type: "tuple",
        internalType: "struct PoolKey",
        components: [
          { name: "token0", type: "address", internalType: "address" },
          { name: "token1", type: "address", internalType: "address" },
          { name: "config", type: "bytes32", internalType: "PoolConfig" },
        ],
      },
      { name: "", type: "bytes32", internalType: "PositionId" },
      { name: "", type: "int128", internalType: "int128" },
    ],
    outputs: [],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "creatorFeeSalt",
    inputs: [{ name: "poolId", type: "bytes32", internalType: "PoolId" }],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "feeAt",
    inputs: [{ name: "poolId", type: "bytes32", internalType: "PoolId" }],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "forwarded_2374103877",
    inputs: [{ name: "original", type: "bytes32", internalType: "Locker" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getLaunch",
    inputs: [{ name: "poolId", type: "bytes32", internalType: "PoolId" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct ScheduledLaunch.Launch",
        components: [
          { name: "owner", type: "address", internalType: "address" },
          { name: "token", type: "address", internalType: "address" },
          { name: "startTime", type: "uint64", internalType: "uint64" },
          { name: "endTime", type: "uint64", internalType: "uint64" },
          { name: "totalSupply", type: "uint128", internalType: "uint128" },
          { name: "deployed", type: "uint128", internalType: "uint128" },
          { name: "targetTick", type: "int32", internalType: "int32" },
          { name: "positionId", type: "bytes32", internalType: "PositionId" },
          { name: "complete", type: "bool", internalType: "bool" },
          { name: "initialFee", type: "uint64", internalType: "uint64" },
          { name: "finalFee", type: "uint64", internalType: "uint64" },
          { name: "migrationLower", type: "uint96", internalType: "SqrtRatio" },
          { name: "migrationUpper", type: "uint96", internalType: "SqrtRatio" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "locked_6416899205",
    inputs: [{ name: "id", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "released",
    inputs: [{ name: "poolId", type: "bytes32", internalType: "PoolId" }],
    outputs: [{ name: "", type: "uint128", internalType: "uint128" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "terminalPool",
    inputs: [
      {
        name: "key",
        type: "tuple",
        internalType: "struct PoolKey",
        components: [
          { name: "token0", type: "address", internalType: "address" },
          { name: "token1", type: "address", internalType: "address" },
          { name: "config", type: "bytes32", internalType: "PoolConfig" },
        ],
      },
    ],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct PoolKey",
        components: [
          { name: "token0", type: "address", internalType: "address" },
          { name: "token1", type: "address", internalType: "address" },
          { name: "config", type: "bytes32", internalType: "PoolConfig" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "CreatorFeesClaimed",
    inputs: [
      {
        name: "poolId",
        type: "bytes32",
        indexed: true,
        internalType: "PoolId",
      },
      {
        name: "recipient",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount0",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "amount1",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "LaunchAdvanced",
    inputs: [
      {
        name: "poolId",
        type: "bytes32",
        indexed: true,
        internalType: "PoolId",
      },
      {
        name: "deployed",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "reserve0",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "reserve1",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      { name: "complete", type: "bool", indexed: false, internalType: "bool" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "LaunchCreated",
    inputs: [
      {
        name: "poolId",
        type: "bytes32",
        indexed: true,
        internalType: "PoolId",
      },
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "owner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "config",
        type: "tuple",
        indexed: false,
        internalType: "struct ScheduledLaunch.LaunchConfig",
        components: [
          { name: "owner", type: "address", internalType: "address" },
          { name: "quoteToken", type: "address", internalType: "address" },
          { name: "name", type: "string", internalType: "string" },
          { name: "symbol", type: "string", internalType: "string" },
          { name: "decimals", type: "uint8", internalType: "uint8" },
          { name: "totalSupply", type: "uint128", internalType: "uint128" },
          { name: "startTime", type: "uint64", internalType: "uint64" },
          { name: "endTime", type: "uint64", internalType: "uint64" },
          { name: "targetTick", type: "int32", internalType: "int32" },
          { name: "upperTick", type: "int32", internalType: "int32" },
          { name: "tickSpacing", type: "uint32", internalType: "uint32" },
          { name: "initialFee", type: "uint64", internalType: "uint64" },
          { name: "finalFee", type: "uint64", internalType: "uint64" },
          { name: "migrationTickLower", type: "int32", internalType: "int32" },
          { name: "migrationTickUpper", type: "int32", internalType: "int32" },
        ],
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "LaunchSwapped",
    inputs: [
      {
        name: "poolId",
        type: "bytes32",
        indexed: true,
        internalType: "PoolId",
      },
      {
        name: "locker",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "delta0",
        type: "int128",
        indexed: false,
        internalType: "int128",
      },
      {
        name: "delta1",
        type: "int128",
        indexed: false,
        internalType: "int128",
      },
      {
        name: "feeAmount",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "feeIsToken1",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "BaseForwardeeAccountantOnly", inputs: [] },
  { type: "error", name: "BaseLockerAccountantOnly", inputs: [] },
  { type: "error", name: "BoundsOrder", inputs: [] },
  { type: "error", name: "BoundsTickSpacing", inputs: [] },
  { type: "error", name: "CallPointNotImplemented", inputs: [] },
  { type: "error", name: "CoreOnly", inputs: [] },
  { type: "error", name: "ExpectedRevertWithinLock", inputs: [] },
  { type: "error", name: "InitializationThroughForwardOnly", inputs: [] },
  { type: "error", name: "InvalidCenterTick", inputs: [] },
  { type: "error", name: "InvalidLaunch", inputs: [] },
  { type: "error", name: "InvalidStableswapAmplification", inputs: [] },
  {
    type: "error",
    name: "InvalidTick",
    inputs: [{ name: "tick", type: "int32", internalType: "int32" }],
  },
  { type: "error", name: "InvalidTickSpacing", inputs: [] },
  { type: "error", name: "InvalidTwamm", inputs: [] },
  { type: "error", name: "LaunchEnded", inputs: [] },
  { type: "error", name: "LaunchNotStarted", inputs: [] },
  { type: "error", name: "MinMaxBounds", inputs: [] },
  { type: "error", name: "OwnerOnly", inputs: [] },
  { type: "error", name: "PositionsThroughExtensionOnly", inputs: [] },
  { type: "error", name: "StableswapMustBeFullRange", inputs: [] },
  { type: "error", name: "SwapsThroughForwardOnly", inputs: [] },
  { type: "error", name: "UnknownLaunch", inputs: [] },
] as const;

export const LOCKED_LAUNCH_LIQUIDITY_ABI = [
  {
    type: "constructor",
    inputs: [
      { name: "core", type: "address", internalType: "contract ICore" },
      { name: "extension", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "EXTENSION",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "createToken",
    inputs: [
      { name: "name", type: "string", internalType: "string" },
      { name: "symbol", type: "string", internalType: "string" },
      { name: "decimals", type: "uint8", internalType: "uint8" },
      { name: "supply", type: "uint128", internalType: "uint128" },
    ],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "creatorFeeSalt",
    inputs: [{ name: "launchId", type: "bytes32", internalType: "PoolId" }],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "forwarded_2374103877",
    inputs: [{ name: "original", type: "bytes32", internalType: "Locker" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getTerminal",
    inputs: [{ name: "launchId", type: "bytes32", internalType: "PoolId" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct LockedLaunchLiquidity.Terminal",
        components: [
          { name: "owner", type: "address", internalType: "address" },
          {
            name: "poolKey",
            type: "tuple",
            internalType: "struct PoolKey",
            components: [
              { name: "token0", type: "address", internalType: "address" },
              { name: "token1", type: "address", internalType: "address" },
              { name: "config", type: "bytes32", internalType: "PoolConfig" },
            ],
          },
          { name: "lower", type: "uint96", internalType: "SqrtRatio" },
          { name: "upper", type: "uint96", internalType: "SqrtRatio" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "locked_6416899205",
    inputs: [{ name: "id", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "migrate",
    inputs: [{ name: "launchId", type: "bytes32", internalType: "PoolId" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "positionId",
    inputs: [{ name: "launchId", type: "bytes32", internalType: "PoolId" }],
    outputs: [{ name: "", type: "bytes32", internalType: "PositionId" }],
    stateMutability: "pure",
  },
  {
    type: "event",
    name: "FeesClaimed",
    inputs: [
      {
        name: "launchId",
        type: "bytes32",
        indexed: true,
        internalType: "PoolId",
      },
      {
        name: "recipient",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount0",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "amount1",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "LiquidityLocked",
    inputs: [
      {
        name: "launchId",
        type: "bytes32",
        indexed: true,
        internalType: "PoolId",
      },
      {
        name: "terminalPoolId",
        type: "bytes32",
        indexed: true,
        internalType: "PoolId",
      },
      {
        name: "liquidity",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PrincipalReceived",
    inputs: [
      {
        name: "launchId",
        type: "bytes32",
        indexed: true,
        internalType: "PoolId",
      },
      { name: "from", type: "address", indexed: true, internalType: "address" },
      {
        name: "amount0",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "amount1",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "BaseForwardeeAccountantOnly", inputs: [] },
  { type: "error", name: "BaseLockerAccountantOnly", inputs: [] },
  { type: "error", name: "CoreOnly", inputs: [] },
  { type: "error", name: "ExpectedRevertWithinLock", inputs: [] },
  { type: "error", name: "ExtensionOnly", inputs: [] },
  {
    type: "error",
    name: "InvalidTick",
    inputs: [{ name: "tick", type: "int32", internalType: "int32" }],
  },
  { type: "error", name: "OwnerOnly", inputs: [] },
  { type: "error", name: "UnknownLaunch", inputs: [] },
] as const;

export const LAUNCH_ROUTER_ABI = [
  {
    type: "constructor",
    inputs: [
      { name: "core", type: "address", internalType: "contract ICore" },
      {
        name: "extension",
        type: "address",
        internalType: "contract ScheduledLaunch",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "EXTENSION",
    inputs: [],
    outputs: [
      { name: "", type: "address", internalType: "contract ScheduledLaunch" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "LIQUIDITY",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract LockedLaunchLiquidity",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "claimFees",
    inputs: [
      {
        name: "key",
        type: "tuple",
        internalType: "struct PoolKey",
        components: [
          { name: "token0", type: "address", internalType: "address" },
          { name: "token1", type: "address", internalType: "address" },
          { name: "config", type: "bytes32", internalType: "PoolConfig" },
        ],
      },
      { name: "recipient", type: "address", internalType: "address" },
    ],
    outputs: [
      { name: "amount0", type: "uint128", internalType: "uint128" },
      { name: "amount1", type: "uint128", internalType: "uint128" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "create",
    inputs: [
      {
        name: "config",
        type: "tuple",
        internalType: "struct ScheduledLaunch.LaunchConfig",
        components: [
          { name: "owner", type: "address", internalType: "address" },
          { name: "quoteToken", type: "address", internalType: "address" },
          { name: "name", type: "string", internalType: "string" },
          { name: "symbol", type: "string", internalType: "string" },
          { name: "decimals", type: "uint8", internalType: "uint8" },
          { name: "totalSupply", type: "uint128", internalType: "uint128" },
          { name: "startTime", type: "uint64", internalType: "uint64" },
          { name: "endTime", type: "uint64", internalType: "uint64" },
          { name: "targetTick", type: "int32", internalType: "int32" },
          { name: "upperTick", type: "int32", internalType: "int32" },
          { name: "tickSpacing", type: "uint32", internalType: "uint32" },
          { name: "initialFee", type: "uint64", internalType: "uint64" },
          { name: "finalFee", type: "uint64", internalType: "uint64" },
          { name: "migrationTickLower", type: "int32", internalType: "int32" },
          { name: "migrationTickUpper", type: "int32", internalType: "int32" },
        ],
      },
    ],
    outputs: [
      {
        name: "key",
        type: "tuple",
        internalType: "struct PoolKey",
        components: [
          { name: "token0", type: "address", internalType: "address" },
          { name: "token1", type: "address", internalType: "address" },
          { name: "config", type: "bytes32", internalType: "PoolConfig" },
        ],
      },
      { name: "token", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "creator",
    inputs: [{ name: "launchId", type: "bytes32", internalType: "PoolId" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "fund",
    inputs: [
      { name: "launchId", type: "bytes32", internalType: "PoolId" },
      { name: "amount0", type: "uint128", internalType: "uint128" },
      { name: "amount1", type: "uint128", internalType: "uint128" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "locked_6416899205",
    inputs: [{ name: "id", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "LaunchCreatedBy",
    inputs: [
      {
        name: "launchId",
        type: "bytes32",
        indexed: true,
        internalType: "PoolId",
      },
      {
        name: "creator",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "BaseLockerAccountantOnly", inputs: [] },
  { type: "error", name: "CreatorOnly", inputs: [] },
  { type: "error", name: "ExpectedRevertWithinLock", inputs: [] },
  { type: "error", name: "InvalidPayment", inputs: [] },
  { type: "error", name: "InvalidRecipient", inputs: [] },
] as const;
